### ISSUE TITLE
Clojure + Crux

### ISSUE THREAD

**Issue by deobald** [pariyatti/kosa#11]
### infra

- [x] initial setup? -- :+1: 
- [x] deployment story?
- [x] unit tests? -- @holtzermann17 will try `spec` generative tests
- [x] acceptance tests?

### database

0. [x] **Upgrade to 1.12:** It's the new hotness.
1. [x] **One-to-Many:**
    - [x] 1-N relationships for pali word & translations -- vector internal to the pali word doc
    - [x] stacked inspiration -- (N-1) -- image
2. [x] **Schema:** `crux-schema` or `spec` for tabular entities for mobile app front-end API data
    - [x] inserting (try it out for the "New Pali Word Card" screen): Manual validation works fine
    - [x] schema / data migration
3. [x] **Model Time:** 3rd tier time model for ancient publication dates? (parallel to `valid-time`)
4. [x] **Chained Relations:** What do the queries look like over A->B->C->D ?
5. [x] **Reify Relationship:** graph-shaped documents with named (doc) relationships?
    - [x] Answer: mostly no. Just use "vertex duck-typing" by creating meaningful ids on each entity.
6. [x] **File Uploads:**
    - [x] what do db fields look like?
    - [x] what happens when we switch disk storage? (local disk / S3 / cloudflare / etc)

### code (non-database)

1. [x] **Javascript:**
    - [x] install `clr-icons` from `npm` during deployment rather than vendoring otherwise we get source map errors
    - [x] ClojureScript or vanilla JS?
2. [x] **File Uploads:**
    - [x] the [luminous / bulma approach](https://luminusweb.com/docs/routes.html#handling_file_uploads) seems entirely legit

### rails parity

1. [x] how hard is it to migrate Rails ERB templates? -- not too bad. use [html2hiccup](http://html2hiccup.buttercloud.com)
2. [x] dev vs. test environments? -- method mostly borrowed from nilenso approach (`/config/config.test.edn` etc)
3. [x] replace all html, css, controller behaviour, model behaviour -- chore for @deobald 

### fun stuff

- [x] enhance `reitit` route conflict handling. ... checked off, but I did not actually finish this since it's not of immediate value to the Pariyatti project. - @deobald 

From ikitommi in #reitit clojurians slack:

```
the conflict resolver could be smarter and know that
[["/kikka/kikka"]
 ["/kikka/:id"]]
actually is not conflicting as the fixed term(s) comes first. PR welcome :)
```
